server:
  port: 9191
spring:  h2:    console:      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb2
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect 
  application:    name: PAYMENT-SERVICE  
    
    
eureka:  client:    register-with-eureka: true
    fetch-registry: true
    service-url:      defaultZone: http://localhost:8761/eureka/
  instance:    hostname: localhost          